// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qandil.Infrastructure.Data;

#nullable disable

namespace Qandil.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qandil.Core.Entity.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDisability")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("Qandil.Core.Entity.ChildTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("TestId");

                    b.ToTable("ChildTests");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildTestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChildTestId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DisabilityOnsetDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicalNots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Qandil.Core.Entity.DiagnosisDisability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiagnosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DisabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("DisabilityId");

                    b.ToTable("DiagnosisDisabilities");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Disability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Disabilities");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specicality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Qandil.Core.Entity.ReEvalution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ReEvalutions");
                });

            modelBuilder.Entity("Qandil.Core.Entity.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Qandil.Core.Entity.SupportivSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nmae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SupportivSessions");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("testType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Tracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrentSchool")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique()
                        .HasFilter("[ChildId] IS NOT NULL");

                    b.HasIndex("SchoolId");

                    b.ToTable("Trackings");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Child", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Classroom", "Classroom")
                        .WithMany("Children")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.Program", "Program")
                        .WithMany("Children")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Classroom");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Qandil.Core.Entity.ChildTest", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Child", "Child")
                        .WithMany("ChildTests")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Qandil.Core.Entity.Test", "Test")
                        .WithMany("ChildTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Classroom", b =>
                {
                    b.HasOne("Qandil.Core.Entity.ChildTest", "ChildTest")
                        .WithMany()
                        .HasForeignKey("ChildTestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.Employee", "Employee")
                        .WithMany("Classrooms")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.Level", "Level")
                        .WithMany("Classrooms")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.Program", "Program")
                        .WithMany("Classrooms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ChildTest");

                    b.Navigation("Employee");

                    b.Navigation("Level");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Diagnosis", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Child", "Child")
                        .WithOne("Diagnosis")
                        .HasForeignKey("Qandil.Core.Entity.Diagnosis", "ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Qandil.Core.Entity.Employee", "Employee")
                        .WithMany("Diagnoses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Qandil.Core.Entity.DiagnosisDisability", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Diagnosis", "Diagnosis")
                        .WithMany("DiagnosisDisabilities")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Qandil.Core.Entity.Disability", "Disability")
                        .WithMany("DiagnosisDisabilities")
                        .HasForeignKey("DisabilityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Disability");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Level", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Program", "Program")
                        .WithMany("Levels")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Qandil.Core.Entity.ReEvalution", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Diagnosis", "Diagnosis")
                        .WithMany("ReEvalutions")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.Employee", "Employee")
                        .WithMany("ReEvalutions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Diagnosis");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Qandil.Core.Entity.SupportivSession", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Child", "Child")
                        .WithMany("SupportivSessions")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.Employee", null)
                        .WithMany("SupportivSessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Test", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Employee", null)
                        .WithMany("Tests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Qandil.Core.Entity.Tracking", b =>
                {
                    b.HasOne("Qandil.Core.Entity.Child", "Child")
                        .WithOne("Tracking")
                        .HasForeignKey("Qandil.Core.Entity.Tracking", "ChildId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Qandil.Core.Entity.School", "School")
                        .WithMany("trackings")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Child");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Child", b =>
                {
                    b.Navigation("ChildTests");

                    b.Navigation("Diagnosis");

                    b.Navigation("SupportivSessions");

                    b.Navigation("Tracking");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Classroom", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Diagnosis", b =>
                {
                    b.Navigation("DiagnosisDisabilities");

                    b.Navigation("ReEvalutions");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Disability", b =>
                {
                    b.Navigation("DiagnosisDisabilities");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Employee", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Diagnoses");

                    b.Navigation("ReEvalutions");

                    b.Navigation("SupportivSessions");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Level", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Program", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Classrooms");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Qandil.Core.Entity.School", b =>
                {
                    b.Navigation("trackings");
                });

            modelBuilder.Entity("Qandil.Core.Entity.Test", b =>
                {
                    b.Navigation("ChildTests");
                });
#pragma warning restore 612, 618
        }
    }
}
